version: "3.7"

services:
  telegram_bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: telebot-v1
    environment:
      TOKEN: 1543075321:AAGu6MIPJ0JwxqTA6XESuCy6818By3anTpU 
    restart: always
    links:
      - redis_database

  redis_database:
    image: redis
    ports:
    - "6379:6379"
    environment:
      HOST: redis_database
